source 'https://rubygems.org'
gem 'addressable'
gem 'async-websocket', '~>0.8.0'
gem 'celluloid-io'
gem 'dotenv'
gem 'faraday'
gem 'puma'
gem 'rack'
gem 'rss'
gem 'rubocop', '~>0.81.0'
gem 'slack-ruby-bot'
